In [5]:
import pandas as pd 
import numpy as np 

df = pd.read_excel('dados/economi.xlsx')

display(df)
display(df.head())
display(list(df.columns)) #descreve o nome das colunas em uma lista 
display(df.info())
display(df.describe())

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020,103.665,0.98913,101.453,NaN
1,2020T2,2020,107.297,0.97758,100.382,NaN
2,2020T3,2020,111.334,0.95334,100.716,NaN
3,2020T4,2020,115.307,0.94183,101.323,NaN
4,2021T1,2021,117.442,0.94028,102.656,NaN
5,2021T2,2021,119.981,0.94031,104.194,NaN
6,2021T3,2021,121.833,0.94807,105.601,NaN
7,2021T4,2021,123.789,0.95386,106.626,NaN
8,2022T1,2022,126.473,0.95405,107.637,NaN
9,2022T2,2022,129.152,0.96242,108.359,NaN
10,2022T3,2022,131.163,0.97666,109.301,NaN
11,2022T4,2022,134.045,0.97552,110.694,NaN
12,2023T1,2023,136.819,0.98957,111.050,NaN
13,2023T2,2023,139.228,0.98663,112.385,NaN
14,2023T3,2023,141.662,1.00162,113.228,NaN
15,2023T4,2023,144.555,1.01500,113.892,NaN
16,2024T1,2024,147.286,1.03037,114.954,NaN
17,2024T2,2024,149.867,1.03176,116.384,NaN
18,2024T3,2024,152.317,1.04009,117.509,NaN
19,2024T4,2024,155.192,1.03863,118.790,NaN
20,2025T1,2025,158.515,1.04110,119.619,NaN
21,2025T2,2025,161.902,1.04897,120.370,NaN
22,2025T3,2025,164.341,1.06058,121.233,NaN
23,2025T4,2025,167.344,1.06212,122.518,NaN

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020,103.665,0.98913,101.453,NaN
1,2020T2,2020,107.297,0.97758,100.382,NaN
2,2020T3,2020,111.334,0.95334,100.716,NaN
3,2020T4,2020,115.307,0.94183,101.323,NaN
4,2021T1,2021,117.442,0.94028,102.656,NaN

['Trimestre',
 'Ano',
 'M - oferta monetaria',
 'V - velocidade',
 'Y - produto real',
 'P - nivel de precos']

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trimestre             24 non-null     str
 1   Ano                   24 non-null     int64
 2   M - oferta monetaria  24 non-null     float64
 3   V - velocidade        24 non-null     float64
 4   Y - produto real      24 non-null     float64
 5   P - nivel de precos   0 non-null      float64
dtypes: float64(4), int64(1), str(1)
memory usage: 1.4 KB

None

,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
count,24.000000,24.000000,24.000000,24.00000,0.0
mean,2022.500000,135.854542,0.994145,110.86975,NaN
std,1.744557,18.714439,0.041254,7.07340,NaN
min,2020.000000,103.665000,0.940280,100.38200,NaN
25%,2021.000000,121.370000,0.954002,105.24925,NaN
50%,2022.500000,135.432000,0.987880,110.87200,NaN
75%,2024.000000,150.479500,1.033478,116.66525,NaN
max,2025.000000,167.344000,1.062120,122.51800,NaN

In [17]:
#seleção de colunas
display(df[['Ano', 'M - oferta monetaria']].head())

# tipos de dados
df['Ano'] = pd.to_datetime(df['Ano'], format='%Y')

display(df.info())


#Calculo de matemática entre colunas
df['P - nivel de precos'] = df['M - oferta monetaria'] * df['V - velocidade'] / df['Y - produto real']

display(df.head())

         Ano  M - oferta monetaria
0 2020-01-01               103.665
1 2020-01-01               107.297
2 2020-01-01               111.334
3 2020-01-01               115.307
4 2021-01-01               117.442

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trimestre             24 non-null     str
 1   Ano                   24 non-null     datetime64[us]
 2   M - oferta monetaria  24 non-null     float64
 3   V - velocidade        24 non-null     float64
 4   Y - produto real      24 non-null     float64
 5   P - nivel de precos   24 non-null     float64
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 1.4 KB

None

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos
0,2020T1,2020-01-01,103.665,0.98913,101.453,1.010696
1,2020T2,2020-01-01,107.297,0.97758,100.382,1.044922
2,2020T3,2020-01-01,111.334,0.95334,100.716,1.053846
3,2020T4,2020-01-01,115.307,0.94183,101.323,1.071816
4,2021T1,2021-01-01,117.442,0.94028,102.656,1.075713

In [ ]:
# criar nova coluna

df['Taxa de crescimento - M'] = df['M - oferta monetaria'].pct_change() * 100

diferenca_m = df['Taxa de crescimento - M'] / 100

df['Media de crescimento - M'] = diferenca_m.mean() # média

display(df)

,Trimestre,Ano,M - oferta monetaria,V - velocidade,Y - produto real,P - nivel de precos,Taxa de crescimento - M,Media de crescimento - M
0,2020T1,2020-01-01,103.665,0.98913,101.453,1.010696,NaN,0.021058
1,2020T2,2020-01-01,107.297,0.97758,100.382,1.044922,3.503593,0.021058
2,2020T3,2020-01-01,111.334,0.95334,100.716,1.053846,3.762454,0.021058
3,2020T4,2020-01-01,115.307,0.94183,101.323,1.071816,3.568542,0.021058
4,2021T1,2021-01-01,117.442,0.94028,102.656,1.075713,1.851579,0.021058
5,2021T2,2021-01-01,119.981,0.94031,104.194,1.082781,2.161918,0.021058
6,2021T3,2021-01-01,121.833,0.94807,105.601,1.093798,1.543578,0.021058
7,2021T4,2021-01-01,123.789,0.95386,106.626,1.107398,1.605476,0.021058
8,2022T1,2022-01-01,126.473,0.95405,107.637,1.121005,2.168206,0.021058
9,2022T2,2022-01-01,129.152,0.96242,108.359,1.147099,2.118239,0.021058
10,2022T3,2022-01-01,131.163,0.97666,109.301,1.172008,1.557080,0.021058
11,2022T4,2022-01-01,134.045,0.97552,110.694,1.181307,2.197266,0.021058
12,2023T1,2023-01-01,136.819,0.98957,111.050,1.219198,2.069454,0.021058
13,2023T2,2023-01-01,139.228,0.98663,112.385,1.222285,1.760720,0.021058
14,2023T3,2023-01-01,141.662,1.00162,113.228,1.253148,1.748212,0.021058
15,2023T4,2023-01-01,144.555,1.01500,113.892,1.288267,2.042185,0.021058
16,2024T1,2024-01-01,147.286,1.03037,114.954,1.320172,1.889246,0.021058
17,2024T2,2024-01-01,149.867,1.03176,116.384,1.328591,1.752373,0.021058
18,2024T3,2024-01-01,152.317,1.04009,117.509,1.348181,1.634783,0.021058
19,2024T4,2024-01-01,155.192,1.03863,118.790,1.356908,1.887511,0.021058
20,2025T1,2025-01-01,158.515,1.04110,119.619,1.379630,2.141219,0.021058
21,2025T2,2025-01-01,161.902,1.04897,120.370,1.410903,2.136706,0.021058
22,2025T3,2025-01-01,164.341,1.06058,121.233,1.437701,1.506467,0.021058
23,2025T4,2025-01-01,167.344,1.06212,122.518,1.450721,1.827298,0.021058